# Generated by Django 5.2.14 on 2026-05-18 08:01

import apps.accounts.managers
import core.security.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('email',),
                'indexes': [models.Index(fields=['role'], name='accounts_user_role_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
