# Generated by Django 5.2.14 on 2026-05-18 08:38

import core.security.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_by_email', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan Error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
