# Generated by Django 5.2.14 on 2026-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_inline_image',
            field=models.BooleanField(default=False),
        ),
    ]
