# Generated by Django 5.2.14 on 2026-05-18 08:38

import core.security.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('channel', models.CharField(choices=[('hackerone', 'HackerOne'), ('ghsa', 'GitHub Security Advisory'), ('mitre', 'MITRE / CNA'), ('patchstack', 'Patchstack'), ('asf_security', 'Apache Security'), ('email_vendor', 'Vendor Email'), ('other', 'Other')], max_length=20)),
                ('channel_program', models.CharField(blank=True, max_length=100)),
                ('cve_id', models.CharField(blank=True, max_length=30)),
                ('reported_by_email', models.CharField(blank=True, max_length=255)),
                ('cvss_31_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_31_vector', models.CharField(blank=True, max_length=200)),
                ('cvss_4_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cvss_4_vector', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='none', editable=False, max_length=10)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('in_triage', 'In Triage'), ('vendor_ack', 'Vendor Acknowledged'), ('patched', 'Patched'), ('awaiting_cve', 'Awaiting CVE'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('wontfix', "Won't Fix"), ('wad', 'Working As Designed')], db_index=True, default='drafted', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cwe_ids', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('disclosed_at', models.DateField(blank=True, null=True)),
                ('acknowledged_at', models.DateField(blank=True, null=True)),
                ('patched_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_researchers', models.ManyToManyField(blank=True, related_name='findings_assigned', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='engagements.engagement')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings_reported', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='vendors.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FindingNote',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_notes', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='findings.finding')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', '-created_at'], name='finding_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['vendor'], name='finding_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['channel'], name='finding_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['severity', '-created_at'], name='finding_sev_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['reported_by'], name='finding_reporter_idx'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('internal_id',), name='finding_internal_id_unique'),
        ),
    ]
