# Generated by Django 5.2.14 on 2026-05-19 20:57

import core.security.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('findings', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingReviewNote',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('author_is_reviewer', models.BooleanField(default=False, help_text='Snapshot of whether the author was a reviewer/superadmin at write time. Used to render reporter-vs-reviewer attribution without re-checking the User row.')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('under_review', 'Under review'), ('approved', 'ZT approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['review_state', '-created_at'], name='finding_review_ts_idx'),
        ),
        migrations.AddField(
            model_name='findingreviewnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_review_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='findingreviewnote',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='findings.finding'),
        ),
    ]
