# Generated by Django 5.2.14 on 2026-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_findingreviewnote_finding_review_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='review_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('in_triage', 'In Triage'), ('vendor_ack', 'Vendor Ack'), ('patched', 'Patched'), ('awaiting_cve', 'Awaiting CVE'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('wontfix', "Won't Fix"), ('wad', 'WAD')], db_index=True, default='drafted', max_length=20),
        ),
    ]
