# Generated by Django 5.2.14 on 2026-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_alter_finding_review_state_alter_finding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='internal_id',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
