# Generated by Django 5.2.14 on 2026-05-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_alter_finding_internal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finding',
            old_name='description',
            new_name='narrative',
        ),
    ]
