# Generated by Django 5.2.14 on 2026-05-27 05:46

import core.security.uuids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_rename_description_finding_narrative'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='poc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='remediation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AffectedHost',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_hosts', to='vendors.vendor')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='affected_hosts',
            field=models.ManyToManyField(blank=True, related_name='findings', to='findings.affectedhost'),
        ),
        migrations.AddConstraint(
            model_name='affectedhost',
            constraint=models.UniqueConstraint(fields=('vendor', 'value'), name='affectedhost_vendor_value_unique'),
        ),
    ]
