# Generated by Django 5.2.14 on 2026-05-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_finding_poc_finding_remediation_affectedhost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='engagement',
        ),
    ]
