# Generated by Django 5.2.14 on 2026-05-18 08:01

import core.security.uuids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('engagement_type', models.CharField(choices=[('bug_bounty', 'Bug Bounty'), ('disclosure', 'Disclosure'), ('pentest', 'Pentest'), ('research', 'Research')], default='disclosure', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('target_vendor', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='engagement_status_ts_idx'), models.Index(fields=['target_vendor'], name='engagement_vendor_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScopeRule',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('in_scope', 'In Scope'), ('out_of_scope', 'Out of Scope')], max_length=20)),
                ('pattern', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_rules', to='engagements.engagement')),
            ],
            options={
                'ordering': ('engagement', 'rule_type', 'pattern'),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('url', 'URL'), ('repo', 'Code Repository'), ('binary', 'Binary'), ('container', 'Container Image'), ('package', 'Package'), ('network_host', 'Network Host'), ('other', 'Other')], max_length=20)),
                ('identifier', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('in_scope', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='engagements.engagement')),
            ],
            options={
                'ordering': ('engagement', 'kind', 'identifier'),
                'indexes': [models.Index(fields=['engagement', 'kind'], name='asset_eng_kind_idx')],
            },
        ),
    ]
