# Generated by Django 5.2.14 on 2026-05-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        # Drop the Finding->Engagement FK before deleting Engagement, so the
        # historical state can still resolve the FK target when 0007 runs.
        ('findings', '0007_remove_finding_engagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoperule',
            name='engagement',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Engagement',
        ),
        migrations.DeleteModel(
            name='ScopeRule',
        ),
    ]
