# Generated by Django 5.2.14 on 2026-05-18 08:01

import core.security.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminApproval',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('register_superadmin', 'Register Superadmin'), ('revoke_user', 'Revoke User')], max_length=50)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('executed', 'Executed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('denied_reason', models.CharField(blank=True, max_length=500)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_error', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_approved', to=settings.AUTH_USER_MODEL)),
                ('denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_denied', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', '-created_at'], name='approvals_state_ts_idx'), models.Index(fields=['requested_by', '-created_at'], name='approvals_req_ts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='approvals_no_self_approval'), models.CheckConstraint(condition=models.Q(('denied_by__isnull', True), models.Q(('denied_by', models.F('requested_by')), _negated=True), _connector='OR'), name='approvals_no_self_denial')],
            },
        ),
    ]
