# Generated by Django 5.2.14 on 2026-05-18 08:01

import core.security.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('superadmin_token_issued', 'Superadmin Token Issued'), ('superadmin_role_granted', 'Superadmin Role Granted'), ('credential_registered', 'Credential Registered'), ('user_signed_in', 'User Signed In'), ('user_signed_out', 'User Signed Out'), ('approval_requested', 'Approval Requested'), ('approval_approved', 'Approval Approved'), ('approval_denied', 'Approval Denied'), ('approval_executed', 'Approval Executed'), ('approval_expired', 'Approval Expired')], db_index=True, max_length=50)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.CharField(blank=True, max_length=500)),
                ('target_kind', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit log entries',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='audit_ts_action_idx'), models.Index(fields=['actor_user', '-timestamp'], name='audit_actor_ts_idx'), models.Index(fields=['target_kind', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
