# Generated by Django 5.2.14 on 2026-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_immutability_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('superadmin_token_issued', 'Superadmin Token Issued'), ('superadmin_role_granted', 'Superadmin Role Granted'), ('credential_registered', 'Credential Registered'), ('user_signed_in', 'User Signed In'), ('user_signed_out', 'User Signed Out'), ('approval_requested', 'Approval Requested'), ('approval_approved', 'Approval Approved'), ('approval_denied', 'Approval Denied'), ('approval_executed', 'Approval Executed'), ('approval_expired', 'Approval Expired')], db_index=True, max_length=50),
        ),
    ]
