# Generated by Django 5.2.14 on 2026-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('superadmin_token_issued', 'Superadmin Token Issued'), ('superadmin_role_granted', 'Superadmin Role Granted'), ('credential_registered', 'Credential Registered'), ('user_signed_in', 'User Signed In'), ('user_signed_out', 'User Signed Out'), ('finding_deleted', 'Finding Deleted'), ('review_started', 'Review Started'), ('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected'), ('approval_requested', 'Approval Requested'), ('approval_approved', 'Approval Approved'), ('approval_denied', 'Approval Denied'), ('approval_executed', 'Approval Executed'), ('approval_expired', 'Approval Expired')], db_index=True, max_length=50),
        ),
    ]
