# Generated by Django 5.2.14 on 2026-05-27 06:25

import core.security.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0007_remove_finding_engagement'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeCategory',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'scope categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('engagement_start', models.DateField(blank=True, null=True)),
                ('engagement_end', models.DateField(blank=True, null=True)),
                ('classification', models.CharField(default='CONFIDENTIAL', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('final', 'Final')], db_index=True, default='draft', max_length=20)),
                ('executive_summary', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='vendors.vendor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('engagement_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_as_manager', to=settings.AUTH_USER_MODEL)),
                ('findings', models.ManyToManyField(blank=True, related_name='reports', to='findings.finding')),
                ('researchers', models.ManyToManyField(blank=True, related_name='reports_as_researcher', to=settings.AUTH_USER_MODEL)),
                ('scope_categories', models.ManyToManyField(blank=True, related_name='reports', to='reports.scopecategory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('security', 'Security'), ('manager', 'Manager'), ('administration', 'Administration'), ('technical', 'Technical'), ('other', 'Other')], default='security', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='reports.report')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Annex',
            fields=[
                ('id', models.UUIDField(default=core.security.uuids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexes', to='reports.report')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
