# Generated by Django 5.2.14 on 2026-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_reviewed_at_report_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopecategory',
            name='methodology',
            field=models.TextField(blank=True),
        ),
    ]
